// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Special is the predicate function for special builders.
type Special func(*sql.Selector)
