version: '3'
services: 
  app: 
    image: ghcr.io/simbafs/sitcon-broadcast:v2.0.0
    container_name: sitcon-broadcast
    ports: 
    - 3000:3000
    restart: always
    environment:
      - TOKEN=TOKEN
      - TZ=Asia/Taipei
      - DOMAIN=localhost:3000
    volumes:
      - ./sitcon.db:/app/sitcon.db
