// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/schema"
	"backend/ent/special"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	specialFields := schema.Special{}.Fields()
	_ = specialFields
	// specialDescData is the schema descriptor for data field.
	specialDescData := specialFields[1].Descriptor()
	// special.DefaultData holds the default value on creation for the data field.
	special.DefaultData = specialDescData.Default.(string)
	// specialDescID is the schema descriptor for id field.
	specialDescID := specialFields[0].Descriptor()
	// special.DefaultID holds the default value on creation for the id field.
	special.DefaultID = specialDescID.Default.(string)
}
