// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/predicate"
	"backend/ent/session"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (su *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetIdx sets the "idx" field.
func (su *SessionUpdate) SetIdx(i int8) *SessionUpdate {
	su.mutation.ResetIdx()
	su.mutation.SetIdx(i)
	return su
}

// SetNillableIdx sets the "idx" field if the given value is not nil.
func (su *SessionUpdate) SetNillableIdx(i *int8) *SessionUpdate {
	if i != nil {
		su.SetIdx(*i)
	}
	return su
}

// AddIdx adds i to the "idx" field.
func (su *SessionUpdate) AddIdx(i int8) *SessionUpdate {
	su.mutation.AddIdx(i)
	return su
}

// SetFinish sets the "finish" field.
func (su *SessionUpdate) SetFinish(b bool) *SessionUpdate {
	su.mutation.SetFinish(b)
	return su
}

// SetNillableFinish sets the "finish" field if the given value is not nil.
func (su *SessionUpdate) SetNillableFinish(b *bool) *SessionUpdate {
	if b != nil {
		su.SetFinish(*b)
	}
	return su
}

// SetStart sets the "start" field.
func (su *SessionUpdate) SetStart(i int64) *SessionUpdate {
	su.mutation.ResetStart()
	su.mutation.SetStart(i)
	return su
}

// SetNillableStart sets the "start" field if the given value is not nil.
func (su *SessionUpdate) SetNillableStart(i *int64) *SessionUpdate {
	if i != nil {
		su.SetStart(*i)
	}
	return su
}

// AddStart adds i to the "start" field.
func (su *SessionUpdate) AddStart(i int64) *SessionUpdate {
	su.mutation.AddStart(i)
	return su
}

// SetEnd sets the "end" field.
func (su *SessionUpdate) SetEnd(i int64) *SessionUpdate {
	su.mutation.ResetEnd()
	su.mutation.SetEnd(i)
	return su
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (su *SessionUpdate) SetNillableEnd(i *int64) *SessionUpdate {
	if i != nil {
		su.SetEnd(*i)
	}
	return su
}

// AddEnd adds i to the "end" field.
func (su *SessionUpdate) AddEnd(i int64) *SessionUpdate {
	su.mutation.AddEnd(i)
	return su
}

// SetTitle sets the "title" field.
func (su *SessionUpdate) SetTitle(s string) *SessionUpdate {
	su.mutation.SetTitle(s)
	return su
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (su *SessionUpdate) SetNillableTitle(s *string) *SessionUpdate {
	if s != nil {
		su.SetTitle(*s)
	}
	return su
}

// SetData sets the "data" field.
func (su *SessionUpdate) SetData(m map[string]interface{}) *SessionUpdate {
	su.mutation.SetData(m)
	return su
}

// AddNextIDs adds the "next" edge to the Session entity by IDs.
func (su *SessionUpdate) AddNextIDs(ids ...int) *SessionUpdate {
	su.mutation.AddNextIDs(ids...)
	return su
}

// AddNext adds the "next" edges to the Session entity.
func (su *SessionUpdate) AddNext(s ...*Session) *SessionUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddNextIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (su *SessionUpdate) Mutation() *SessionMutation {
	return su.mutation
}

// ClearNext clears all "next" edges to the Session entity.
func (su *SessionUpdate) ClearNext() *SessionUpdate {
	su.mutation.ClearNext()
	return su
}

// RemoveNextIDs removes the "next" edge to Session entities by IDs.
func (su *SessionUpdate) RemoveNextIDs(ids ...int) *SessionUpdate {
	su.mutation.RemoveNextIDs(ids...)
	return su
}

// RemoveNext removes "next" edges to Session entities.
func (su *SessionUpdate) RemoveNext(s ...*Session) *SessionUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveNextIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SessionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SessionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Idx(); ok {
		_spec.SetField(session.FieldIdx, field.TypeInt8, value)
	}
	if value, ok := su.mutation.AddedIdx(); ok {
		_spec.AddField(session.FieldIdx, field.TypeInt8, value)
	}
	if value, ok := su.mutation.Finish(); ok {
		_spec.SetField(session.FieldFinish, field.TypeBool, value)
	}
	if value, ok := su.mutation.Start(); ok {
		_spec.SetField(session.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedStart(); ok {
		_spec.AddField(session.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.End(); ok {
		_spec.SetField(session.FieldEnd, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedEnd(); ok {
		_spec.AddField(session.FieldEnd, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Title(); ok {
		_spec.SetField(session.FieldTitle, field.TypeString, value)
	}
	if value, ok := su.mutation.Data(); ok {
		_spec.SetField(session.FieldData, field.TypeJSON, value)
	}
	if su.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedNextIDs(); len(nodes) > 0 && !su.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.NextIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetIdx sets the "idx" field.
func (suo *SessionUpdateOne) SetIdx(i int8) *SessionUpdateOne {
	suo.mutation.ResetIdx()
	suo.mutation.SetIdx(i)
	return suo
}

// SetNillableIdx sets the "idx" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableIdx(i *int8) *SessionUpdateOne {
	if i != nil {
		suo.SetIdx(*i)
	}
	return suo
}

// AddIdx adds i to the "idx" field.
func (suo *SessionUpdateOne) AddIdx(i int8) *SessionUpdateOne {
	suo.mutation.AddIdx(i)
	return suo
}

// SetFinish sets the "finish" field.
func (suo *SessionUpdateOne) SetFinish(b bool) *SessionUpdateOne {
	suo.mutation.SetFinish(b)
	return suo
}

// SetNillableFinish sets the "finish" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableFinish(b *bool) *SessionUpdateOne {
	if b != nil {
		suo.SetFinish(*b)
	}
	return suo
}

// SetStart sets the "start" field.
func (suo *SessionUpdateOne) SetStart(i int64) *SessionUpdateOne {
	suo.mutation.ResetStart()
	suo.mutation.SetStart(i)
	return suo
}

// SetNillableStart sets the "start" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableStart(i *int64) *SessionUpdateOne {
	if i != nil {
		suo.SetStart(*i)
	}
	return suo
}

// AddStart adds i to the "start" field.
func (suo *SessionUpdateOne) AddStart(i int64) *SessionUpdateOne {
	suo.mutation.AddStart(i)
	return suo
}

// SetEnd sets the "end" field.
func (suo *SessionUpdateOne) SetEnd(i int64) *SessionUpdateOne {
	suo.mutation.ResetEnd()
	suo.mutation.SetEnd(i)
	return suo
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableEnd(i *int64) *SessionUpdateOne {
	if i != nil {
		suo.SetEnd(*i)
	}
	return suo
}

// AddEnd adds i to the "end" field.
func (suo *SessionUpdateOne) AddEnd(i int64) *SessionUpdateOne {
	suo.mutation.AddEnd(i)
	return suo
}

// SetTitle sets the "title" field.
func (suo *SessionUpdateOne) SetTitle(s string) *SessionUpdateOne {
	suo.mutation.SetTitle(s)
	return suo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableTitle(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetTitle(*s)
	}
	return suo
}

// SetData sets the "data" field.
func (suo *SessionUpdateOne) SetData(m map[string]interface{}) *SessionUpdateOne {
	suo.mutation.SetData(m)
	return suo
}

// AddNextIDs adds the "next" edge to the Session entity by IDs.
func (suo *SessionUpdateOne) AddNextIDs(ids ...int) *SessionUpdateOne {
	suo.mutation.AddNextIDs(ids...)
	return suo
}

// AddNext adds the "next" edges to the Session entity.
func (suo *SessionUpdateOne) AddNext(s ...*Session) *SessionUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddNextIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (suo *SessionUpdateOne) Mutation() *SessionMutation {
	return suo.mutation
}

// ClearNext clears all "next" edges to the Session entity.
func (suo *SessionUpdateOne) ClearNext() *SessionUpdateOne {
	suo.mutation.ClearNext()
	return suo
}

// RemoveNextIDs removes the "next" edge to Session entities by IDs.
func (suo *SessionUpdateOne) RemoveNextIDs(ids ...int) *SessionUpdateOne {
	suo.mutation.RemoveNextIDs(ids...)
	return suo
}

// RemoveNext removes "next" edges to Session entities.
func (suo *SessionUpdateOne) RemoveNext(s ...*Session) *SessionUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveNextIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (suo *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Session entity.
func (suo *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Idx(); ok {
		_spec.SetField(session.FieldIdx, field.TypeInt8, value)
	}
	if value, ok := suo.mutation.AddedIdx(); ok {
		_spec.AddField(session.FieldIdx, field.TypeInt8, value)
	}
	if value, ok := suo.mutation.Finish(); ok {
		_spec.SetField(session.FieldFinish, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Start(); ok {
		_spec.SetField(session.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedStart(); ok {
		_spec.AddField(session.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.End(); ok {
		_spec.SetField(session.FieldEnd, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedEnd(); ok {
		_spec.AddField(session.FieldEnd, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Title(); ok {
		_spec.SetField(session.FieldTitle, field.TypeString, value)
	}
	if value, ok := suo.mutation.Data(); ok {
		_spec.SetField(session.FieldData, field.TypeJSON, value)
	}
	if suo.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedNextIDs(); len(nodes) > 0 && !suo.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.NextIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   session.NextTable,
			Columns: session.NextPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
