// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/session"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Session is the model entity for the Session schema.
type Session struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Speakers holds the value of the "speakers" field.
	Speakers []string `json:"speakers,omitempty"`
	// Room holds the value of the "room" field.
	Room string `json:"room,omitempty"`
	// Broadcast holds the value of the "broadcast" field.
	Broadcast []string `json:"broadcast,omitempty"`
	// Start holds the value of the "start" field.
	Start time.Time `json:"start,omitempty"`
	// End holds the value of the "end" field.
	End time.Time `json:"end,omitempty"`
	// Slido holds the value of the "slido" field.
	Slido string `json:"slido,omitempty"`
	// Slide holds the value of the "slide" field.
	Slide string `json:"slide,omitempty"`
	// Hackmd holds the value of the "hackmd" field.
	Hackmd       string `json:"hackmd,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Session) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case session.FieldSpeakers, session.FieldBroadcast:
			values[i] = new([]byte)
		case session.FieldID, session.FieldTitle, session.FieldType, session.FieldRoom, session.FieldSlido, session.FieldSlide, session.FieldHackmd:
			values[i] = new(sql.NullString)
		case session.FieldStart, session.FieldEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Session fields.
func (s *Session) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case session.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				s.ID = value.String
			}
		case session.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				s.Title = value.String
			}
		case session.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				s.Type = value.String
			}
		case session.FieldSpeakers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field speakers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.Speakers); err != nil {
					return fmt.Errorf("unmarshal field speakers: %w", err)
				}
			}
		case session.FieldRoom:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room", values[i])
			} else if value.Valid {
				s.Room = value.String
			}
		case session.FieldBroadcast:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field broadcast", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.Broadcast); err != nil {
					return fmt.Errorf("unmarshal field broadcast: %w", err)
				}
			}
		case session.FieldStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start", values[i])
			} else if value.Valid {
				s.Start = value.Time
			}
		case session.FieldEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end", values[i])
			} else if value.Valid {
				s.End = value.Time
			}
		case session.FieldSlido:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slido", values[i])
			} else if value.Valid {
				s.Slido = value.String
			}
		case session.FieldSlide:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slide", values[i])
			} else if value.Valid {
				s.Slide = value.String
			}
		case session.FieldHackmd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hackmd", values[i])
			} else if value.Valid {
				s.Hackmd = value.String
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Session.
// This includes values selected through modifiers, order, etc.
func (s *Session) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Session.
// Note that you need to call Session.Unwrap() before calling this method if this Session
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Session) Update() *SessionUpdateOne {
	return NewSessionClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Session entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Session) Unwrap() *Session {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Session is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Session) String() string {
	var builder strings.Builder
	builder.WriteString("Session(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("title=")
	builder.WriteString(s.Title)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(s.Type)
	builder.WriteString(", ")
	builder.WriteString("speakers=")
	builder.WriteString(fmt.Sprintf("%v", s.Speakers))
	builder.WriteString(", ")
	builder.WriteString("room=")
	builder.WriteString(s.Room)
	builder.WriteString(", ")
	builder.WriteString("broadcast=")
	builder.WriteString(fmt.Sprintf("%v", s.Broadcast))
	builder.WriteString(", ")
	builder.WriteString("start=")
	builder.WriteString(s.Start.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end=")
	builder.WriteString(s.End.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("slido=")
	builder.WriteString(s.Slido)
	builder.WriteString(", ")
	builder.WriteString("slide=")
	builder.WriteString(s.Slide)
	builder.WriteString(", ")
	builder.WriteString("hackmd=")
	builder.WriteString(s.Hackmd)
	builder.WriteByte(')')
	return builder.String()
}

// Sessions is a parsable slice of Session.
type Sessions []*Session
