// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/predicate"
	"backend/ent/special"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpecialUpdate is the builder for updating Special entities.
type SpecialUpdate struct {
	config
	hooks    []Hook
	mutation *SpecialMutation
}

// Where appends a list predicates to the SpecialUpdate builder.
func (su *SpecialUpdate) Where(ps ...predicate.Special) *SpecialUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetData sets the "data" field.
func (su *SpecialUpdate) SetData(s string) *SpecialUpdate {
	su.mutation.SetData(s)
	return su
}

// SetNillableData sets the "data" field if the given value is not nil.
func (su *SpecialUpdate) SetNillableData(s *string) *SpecialUpdate {
	if s != nil {
		su.SetData(*s)
	}
	return su
}

// Mutation returns the SpecialMutation object of the builder.
func (su *SpecialUpdate) Mutation() *SpecialMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpecialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpecialUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpecialUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpecialUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SpecialUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(special.Table, special.Columns, sqlgraph.NewFieldSpec(special.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Data(); ok {
		_spec.SetField(special.FieldData, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{special.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SpecialUpdateOne is the builder for updating a single Special entity.
type SpecialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpecialMutation
}

// SetData sets the "data" field.
func (suo *SpecialUpdateOne) SetData(s string) *SpecialUpdateOne {
	suo.mutation.SetData(s)
	return suo
}

// SetNillableData sets the "data" field if the given value is not nil.
func (suo *SpecialUpdateOne) SetNillableData(s *string) *SpecialUpdateOne {
	if s != nil {
		suo.SetData(*s)
	}
	return suo
}

// Mutation returns the SpecialMutation object of the builder.
func (suo *SpecialUpdateOne) Mutation() *SpecialMutation {
	return suo.mutation
}

// Where appends a list predicates to the SpecialUpdate builder.
func (suo *SpecialUpdateOne) Where(ps ...predicate.Special) *SpecialUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpecialUpdateOne) Select(field string, fields ...string) *SpecialUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Special entity.
func (suo *SpecialUpdateOne) Save(ctx context.Context) (*Special, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpecialUpdateOne) SaveX(ctx context.Context) *Special {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpecialUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpecialUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SpecialUpdateOne) sqlSave(ctx context.Context) (_node *Special, err error) {
	_spec := sqlgraph.NewUpdateSpec(special.Table, special.Columns, sqlgraph.NewFieldSpec(special.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Special.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, special.FieldID)
		for _, f := range fields {
			if !special.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != special.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Data(); ok {
		_spec.SetField(special.FieldData, field.TypeString, value)
	}
	_node = &Special{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{special.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
