// Code generated by ent, DO NOT EDIT.

package session

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldRoom holds the string denoting the room field in the database.
	FieldRoom = "room"
	// FieldBroadcastTo holds the string denoting the broadcastto field in the database.
	FieldBroadcastTo = "broadcast_to"
	// FieldBroadcastFrom holds the string denoting the broadcastfrom field in the database.
	FieldBroadcastFrom = "broadcast_from"
	// FieldStart holds the string denoting the start field in the database.
	FieldStart = "start"
	// FieldEnd holds the string denoting the end field in the database.
	FieldEnd = "end"
	// FieldSpeaker holds the string denoting the speaker field in the database.
	FieldSpeaker = "speaker"
	// FieldQa holds the string denoting the qa field in the database.
	FieldQa = "qa"
	// FieldSlidoID holds the string denoting the slidoid field in the database.
	FieldSlidoID = "slido_id"
	// FieldSlidoAdminLink holds the string denoting the slido_admin_link field in the database.
	FieldSlidoAdminLink = "slido_admin_link"
	// FieldCoWrite holds the string denoting the co_write field in the database.
	FieldCoWrite = "co_write"
	// Table holds the table name of the session in the database.
	Table = "sessions"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldRoom,
	FieldBroadcastTo,
	FieldBroadcastFrom,
	FieldStart,
	FieldEnd,
	FieldSpeaker,
	FieldQa,
	FieldSlidoID,
	FieldSlidoAdminLink,
	FieldCoWrite,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByRoom orders the results by the room field.
func ByRoom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoom, opts...).ToFunc()
}

// ByBroadcastFrom orders the results by the broadcastFrom field.
func ByBroadcastFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBroadcastFrom, opts...).ToFunc()
}

// ByStart orders the results by the start field.
func ByStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStart, opts...).ToFunc()
}

// ByEnd orders the results by the end field.
func ByEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnd, opts...).ToFunc()
}

// BySpeaker orders the results by the speaker field.
func BySpeaker(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeaker, opts...).ToFunc()
}

// ByQa orders the results by the qa field.
func ByQa(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQa, opts...).ToFunc()
}

// BySlidoID orders the results by the slidoID field.
func BySlidoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlidoID, opts...).ToFunc()
}

// BySlidoAdminLink orders the results by the slido_admin_link field.
func BySlidoAdminLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlidoAdminLink, opts...).ToFunc()
}

// ByCoWrite orders the results by the co_write field.
func ByCoWrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoWrite, opts...).ToFunc()
}
