// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeString, Default: ""},
		{Name: "speakers", Type: field.TypeJSON},
		{Name: "room", Type: field.TypeString, Default: ""},
		{Name: "broadcast", Type: field.TypeJSON},
		{Name: "start", Type: field.TypeTime},
		{Name: "end", Type: field.TypeTime},
		{Name: "slido", Type: field.TypeString, Default: ""},
		{Name: "slide", Type: field.TypeString, Default: ""},
		{Name: "hackmd", Type: field.TypeString, Default: ""},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SessionsTable,
	}
)

func init() {
}
