name: Build and deploy

on:
    push:
        branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout GitHub Action
              uses: actions/checkout@main

            - name: Install pnpm
              uses: pnpm/action-setup@v4.1.0
              with:
                  version: 10

            - name: Install dependency
              run: pnpm install

            - name: Build
              run: pnpm run build

            - name: Upload dist folder to GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
